export type TPlacement =
  "top"
  | "bottom"
  | "right"
  | "left"
  | "top-left"
  | "top-right"
  | "left-top"
  | "left-bottom"
  | "right-top"
  | "right-bottom"
  | "bottom-left"
  | "bottom-right"
